# Onion dataset for data visualisation

The dataset contains the monthly prices of onion from 2005 - 2015 across the different states of India

In [40]:
import numpy as np
import pandas as pd
import scipy as sp
import plotly.plotly as py
import plotly.offline as offline
import plotly.graph_objs as go

# offline.init_notebook_mode()

pd.set_option('display.max_rows', 999)
# pd.set_option('precision', 5)

#reading the csv into a dataframe
onion_df =  pd.read_csv('../onion/data/onion.csv')

# trimming all whitespaces from cells
df_obj = onion_df.select_dtypes(['object'])
onion_df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())

onion_df.iloc[:,:]

,market,month,year,quantity,priceMin,priceMax,priceMod,city,state,date,lon,lat
0,ABOHAR(PB),January,2005,2350,404,493,446,ABOHAR,PB,2005-01-01,74.19930,30.14529
1,ABOHAR(PB),January,2006,900,487,638,563,ABOHAR,PB,2006-01-01,74.19930,30.14529
2,ABOHAR(PB),January,2010,790,1283,1592,1460,ABOHAR,PB,2010-01-01,74.19930,30.14529
3,ABOHAR(PB),January,2011,245,3067,3750,3433,ABOHAR,PB,2011-01-01,74.19930,30.14529
4,ABOHAR(PB),January,2012,1035,523,686,605,ABOHAR,PB,2012-01-01,74.19930,30.14529
5,ABOHAR(PB),January,2013,675,1327,1900,1605,ABOHAR,PB,2013-01-01,74.19930,30.14529
6,ABOHAR(PB),January,2014,440,1025,1481,1256,ABOHAR,PB,2014-01-01,74.19930,30.14529
7,ABOHAR(PB),January,2015,1305,1309,1858,1613,ABOHAR,PB,2015-01-01,74.19930,30.14529
8,ABOHAR(PB),February,2005,1400,286,365,324,ABOHAR,PB,2005-02-01,74.19930,30.14529
9,ABOHAR(PB),February,2006,1800,343,411,380,ABOHAR,PB,2006-02-01,74.19930,30.14529
10,ABOHAR(PB),February,2010,555,1143,1460,1322,ABOHAR,PB,2010-02-01,74.19930,30.14529
11,ABOHAR(PB),February,2011,300,950,1400,1125,ABOHAR,PB,2011-02-01,74.19930,30.14529
12,ABOHAR(PB),February,2012,675,510,650,570,ABOHAR,PB,2012-02-01,74.19930,30.14529
13,ABOHAR(PB),February,2013,845,1400,1843,1629,ABOHAR,PB,2013-02-01,74.19930,30.14529
14,ABOHAR(PB),February,2014,1115,831,1163,983,ABOHAR,PB,2014-02-01,74.19930,30.14529
15,ABOHAR(PB),February,2015,1115,1200,1946,1688,ABOHAR,PB,2015-02-01,74.19930,30.14529
16,ABOHAR(PB),March,2005,900,281,357,322,ABOHAR,PB,2005-03-01,74.19930,30.14529
17,ABOHAR(PB),March,2006,3185,359,425,391,ABOHAR,PB,2006-03-01,74.19930,30.14529
18,ABOHAR(PB),March,2010,385,510,878,688,ABOHAR,PB,2010-03-01,74.19930,30.14529
19,ABOHAR(PB),March,2011,850,669,1042,855,ABOHAR,PB,2011-03-01,74.19930,30.14529
20,ABOHAR(PB),March,2012,1295,538,675,608,ABOHAR,PB,2012-03-01,74.19930,30.14529
21,ABOHAR(PB),March,2013,1055,920,1323,1080,ABOHAR,PB,2013-03-01,74.19930,30.14529
22,ABOHAR(PB),March,2014,1300,844,1181,994,ABOHAR,PB,2014-03-01,74.19930,30.14529
23,ABOHAR(PB),March,2015,920,1260,1980,1745,ABOHAR,PB,2015-03-01,74.19930,30.14529
24,ABOHAR(PB),April,2006,2100,326,400,366,ABOHAR,PB,2006-04-01,74.19930,30.14529
25,ABOHAR(PB),April,2010,840,466,755,611,ABOHAR,PB,2010-04-01,74.19930,30.14529
26,ABOHAR(PB),April,2011,495,436,625,553,ABOHAR,PB,2011-04-01,74.19930,30.14529
27,ABOHAR(PB),April,2012,2028,486,709,573,ABOHAR,PB,2012-04-01,74.19930,30.14529
28,ABOHAR(PB),April,2013,932,892,1225,1035,ABOHAR,PB,2013-04-01,74.19930,30.14529
29,ABOHAR(PB),April,2014,670,600,944,772,ABOHAR,PB,2014-04-01,74.19930,30.14529
30,ABOHAR(PB),May,2005,375,390,550,475,ABOHAR,PB,2005-05-01,74.19930,30.14529
31,ABOHAR(PB),May,2006,425,300,460,390,ABOHAR,PB,2006-05-01,74.19930,30.14529
32,ABOHAR(PB),May,2010,2050,391,578,494,ABOHAR,PB,2010-05-01,74.19930,30.14529
33,ABOHAR(PB),May,2011,1010,323,513,444,ABOHAR,PB,2011-05-01,74.19930,30.14529
34,ABOHAR(PB),May,2012,300,250,675,500,ABOHAR,PB,2012-05-01,74.19930,30.14529
35,ABOHAR(PB),May,2013,1410,617,980,814,ABOHAR,PB,2013-05-01,74.19930,30.14529
36,ABOHAR(PB),May,2014,1350,789,1111,953,ABOHAR,PB,2014-05-01,74.19930,30.14529
37,ABOHAR(PB),May,2015,940,1020,1620,1310,ABOHAR,PB,2015-05-01,74.19930,30.14529
38,ABOHAR(PB),June,2005,1250,269,368,318,ABOHAR,PB,2005-06-01,74.19930,30.14529
39,ABOHAR(PB),June,2006,125,200,320,300,ABOHAR,PB,2006-06-01,74.19930,30.14529
40,ABOHAR(PB),June,2007,900,500,800,700,ABOHAR,PB,2007-06-01,74.19930,30.14529
41,ABOHAR(PB),June,2010,2075,363,515,460,ABOHAR,PB,2010-06-01,74.19930,30.14529
42,ABOHAR(PB),June,2011,1895,338,547,469,ABOHAR,PB,2011-06-01,74.19930,30.14529
43,ABOHAR(PB),June,2012,1440,443,650,557,ABOHAR,PB,2012-06-01,74.19930,30.14529
44,ABOHAR(PB),June,2013,1645,853,1297,1110,ABOHAR,PB,2013-06-01,74.19930,30.14529
45,ABOHAR(PB),June,2014,1300,683,1129,942,ABOHAR,PB,2014-06-01,74.19930,30.14529
46,ABOHAR(PB),June,2015,610,957,1829,1457,ABOHAR,PB,2015-06-01,74.19930,30.14529
47,ABOHAR(PB),July,2005,825,319,387,348,ABOHAR,PB,2005-07-01,74.19930,30.14529
48,ABOHAR(PB),July,2007,80,700,850,800,ABOHAR,PB,2007-07-01,74.19930,30.14529
49,ABOHAR(PB),July,2010,2515,481,737,617,ABOHAR,PB,2010-07-01,74.19930,30.14529
50,ABOHAR(PB),July,2011,1235,660,915,780,ABOHAR,PB,2011-07-01,74.19930,30.14529
51,ABOHAR(PB),July,2012,1070,516,780,693,ABOHAR,PB,2012-07-01,74.19930,30.14529
52,ABOHAR(PB),July,2013,1325,1913,2453,2187,ABOHAR,PB,2013-07-01,74.19930,30.14529
53,ABOHAR(PB),July,2014,880,1300,2325,1883,ABOHAR,PB,2014-07-01,74.19930,30.14529
54,ABOHAR(PB),July,2015,795,1008,2000,1517,ABOHAR,PB,2015-07-01,74.19930,30.14529
55,ABOHAR(PB),August,2005,1400,457,543,499,ABOHAR,PB,2005-08-01,74.19930,30.14529
56,ABOHAR(PB),August,2007,60,1400,1650,1500,ABOHAR,PB,2007-08-01,74.19930,30.14529
57,ABOHAR(PB),August,2010,1125,591,1081,877,ABOHAR,PB,2010-08-01,74.19930,30.14529
58,ABOHAR(PB),August,2011,1495,900,1217,1050,ABOHAR,PB,2011-08-01,74.19930,30.14529
59,ABOHAR(PB),August,2012,775,638,913,786,ABOHAR,PB,2012-08-01,74.19930,30.14529
60,ABOHAR(PB),August,2013,1072,3364,3959,3718,ABOHAR,PB,2013-08-01,74.19930,30.14529
61,ABOHAR(PB),August,2014,885,1331,2185,1923,ABOHAR,PB,2014-08-01,74.19930,30.14529
62,ABOHAR(PB),September,2005,2525,896,1048,963,ABOHAR,PB,2005-09-01,74.19930,30.14529
63,ABOHAR(PB),September,2006,125,283,460,417,ABOHAR,PB,2006-09-01,74.19930,30.14529
64,ABOHAR(PB),September,2010,395,836,1528,1318,ABOHAR,PB,2010-09-01,74.19930,30.14529
65,ABOHAR(PB),September,2011,545,925,1406,1225,ABOHAR,PB,2011-09-01,74.19930,30.14529
66,ABOHAR(PB),September,2012,200,517,917,775,ABOHAR,PB,2012-09-01,74.19930,30.14529
67,ABOHAR(PB),September,2013,575,4273,5109,4800,ABOHAR,PB,2013-09-01,74.19930,30.14529
68,ABOHAR(PB),September,2014,1245,1325,2063,1884,ABOHAR,PB,2014-09-01,74.19930,30.14529
69,ABOHAR(PB),October,2005,150,783,1370,1217,ABOHAR,PB,2005-10-01,74.19930,30.14529
70,ABOHAR(PB),October,2009,480,1479,1818,1664,ABOHAR,PB,2009-10-01,74.19930,30.14529
71,ABOHAR(PB),October,2010,435,989,1770,1504,ABOHAR,PB,2010-10-01,74.19930,30.14529
72,ABOHAR(PB),October,2011,970,956,1322,1119,ABOHAR,PB,2011-10-01,74.19930,30.14529
73,ABOHAR(PB),October,2012,315,650,1088,925,ABOHAR,PB,2012-10-01,74.19930,30.14529
74,ABOHAR(PB),October,2013,400,2979,5079,4429,ABOHAR,PB,2013-10-01,74.19930,30.14529
75,ABOHAR(PB),October,2014,535,1314,2136,1914,ABOHAR,PB,2014-10-01,74.19930,30.14529
76,ABOHAR(PB),November,2005,100,600,800,700,ABOHAR,PB,2005-11-01,74.19930,30.14529
77,ABOHAR(PB),November,2009,315,1269,1663,1497,ABOHAR,PB,2009-11-01,74.19930,30.14529
78,ABOHAR(PB),November,2010,320,1321,1892,1633,ABOHAR,PB,2010-11-01,74.19930,30.14529
79,ABOHAR(PB),November,2011,445,800,1200,992,ABOHAR,PB,2011-11-01,74.19930,30.14529
80,ABOHAR(PB),November,2012,675,806,1381,1150,ABOHAR,PB,2012-11-01,74.19930,30.14529
81,ABOHAR(PB),November,2013,575,2250,3600,2867,ABOHAR,PB,2013-11-01,74.19930,30.14529
82,ABOHAR(PB),November,2014,625,1325,2000,1781,ABOHAR,PB,2014-11-01,74.19930,30.14529
83,ABOHAR(PB),December,2005,900,521,670,602,ABOHAR,PB,2005-12-01,74.19930,30.14529
84,ABOHAR(PB),December,2009,335,1292,1581,1450,ABOHAR,PB,2009-12-01,74.19930,30.14529
85,ABOHAR(PB),December,2010,350,2522,3344,3028,ABOHAR,PB,2010-12-01,74.19930,30.14529
86,ABOHAR(PB),December,2011,50,500,800,600,ABOHAR,PB,2011-12-01,74.19930,30.14529
87,ABOHAR(PB),December,2012,310,880,1565,1270,ABOHAR,PB,2012-12-01,74.19930,30.14529
88,ABOHAR(PB),December,2013,470,1675,2356,1938,ABOHAR,PB,2013-12-01,74.19930,30.14529
89,ABOHAR(PB),December,2014,1155,1294,1903,1659,ABOHAR,PB,2014-12-01,74.19930,30.14529
90,AGRA(UP),January,2005,6400,329,424,377,AGRA,UP,2005-01-01,78.00807,27.17667
91,AGRA(UP),January,2006,11175,414,585,549,AGRA,UP,2006-01-01,78.00807,27.17667
92,AGRA(UP),January,2007,10300,762,844,801,AGRA,UP,2007-01-01,78.00807,27.17667
93,AGRA(UP),January,2008,50000,491,567,522,AGRA,UP,2008-01-01,78.00807,27.17667
94,AGRA(UP),January,2009,26500,1220,1327,1259,AGRA,UP,2009-01-01,78.00807,27.17667
95,AGRA(UP),January,2010,45430,1249,1366,1308,AGRA,UP,2010-01-01,78.00807,27.17667
96,AGRA(UP),January,2011,27385,2893,3141,3005,AGRA,UP,2011-01-01,78.00807,27.17667
97,AGRA(UP),January,2012,59900,661,755,715,AGRA,UP,2012-01-01,78.00807,27.17667
98,AGRA(UP),January,2013,64940,1238,1349,1292,AGRA,UP,2013-01-01,78.00807,27.17667
99,AGRA(UP),January,2014,143920,1102,1246,1200,AGRA,UP,2014-01-01,78.00807,27.17667
100,AGRA(UP),January,2015,64990,1587,1746,1693,AGRA,UP,2015-01-01,78.00807,27.17667
101,AGRA(UP),January,2016,134200,1039,1443,1349,AGRA,UP,2016-01-01,78.00807,27.17667
102,AGRA(UP),February,2005,4800,300,390,345,AGRA,UP,2005-02-01,78.00807,27.17667
103,AGRA(UP),February,2006,13400,354,453,412,AGRA,UP,2006-02-01,78.00807,27.17667
104,AGRA(UP),February,2007,8095,983,1093,1051,AGRA,UP,2007-02-01,78.00807,27.17667
105,AGRA(UP),February,2008,84200,320,407,354,AGRA,UP,2008-02-01,78.00807,27.17667
106,AGRA(UP),February,2009,36900,997,1078,1043,AGRA,UP,2009-02-01,78.00807,27.17667
107,AGRA(UP),February,2010,52580,1189,1321,1256,AGRA,UP,2010-02-01,78.00807,27.17667
108,AGRA(UP),February,2011,44110,1287,1424,1371,AGRA,UP,2011-02-01,78.00807,27.17667
109,AGRA(UP),February,2012,62410,602,709,653,AGRA,UP,2012-02-01,78.00807,27.17667
110,AGRA(UP),February,2013,47690,1656,1799,1746,AGRA,UP,2013-02-01,78.00807,27.17667
111,AGRA(UP),February,2014,96950,1111,1225,1177,AGRA,UP,2014-02-01,78.00807,27.17667
112,AGRA(UP),February,2015,56004,1476,1633,1583,AGRA,UP,2015-02-01,78.00807,27.17667
113,AGRA(UP),February,2016,124508,895,1220,1130,AGRA,UP,2016-02-01,78.00807,27.17667
114,AGRA(UP),March,2006,6992,348,405,376,AGRA,UP,2006-03-01,78.00807,27.17667
115,AGRA(UP),March,2007,15550,962,1088,1042,AGRA,UP,2007-03-01,78.00807,27.17667
116,AGRA(UP),March,2008,47550,375,470,423,AGRA,UP,2008-03-01,78.00807,27.17667
117,AGRA(UP),March,2009,43600,1056,1157,1096,AGRA,UP,2009-03-01,78.00807,27.17667
118,AGRA(UP),March,2010,67050,1163,1254,1205,AGRA,UP,2010-03-01,78.00807,27.17667
119,AGRA(UP),March,2011,51810,797,906,877,AGRA,UP,2011-03-01,78.00807,27.17667
120,AGRA(UP),March,2012,64175,611,708,658,AGRA,UP,2012-03-01,78.00807,27.17667
121,AGRA(UP),March,2013,71945,1256,1352,1305,AGRA,UP,2013-03-01,78.00807,27.17667
122,AGRA(UP),March,2014,100060,1048,1189,1146,AGRA,UP,2014-03-01,78.00807,27.17667
123,AGRA(UP),March,2015,56330,1660,1799,1750,AGRA,UP,2015-03-01,78.00807,27.17667
124,AGRA(UP),March,2016,104400,753,1083,1008,AGRA,UP,2016-03-01,78.00807,27.17667
125,AGRA(UP),April,2005,1900,325,375,360,AGRA,UP,2005-04-01,78.00807,27.17667
126,AGRA(UP),April,2006,9230,337,379,361,AGRA,UP,2006-04-01,78.00807,27.17667
127,AGRA(UP),April,2007,25700,533,616,566,AGRA,UP,2007-04-01,78.00807,27.17667
128,AGRA(UP),April,2008,42650,385,469,418,AGRA,UP,2008-04-01,78.00807,27.17667
129,AGRA(UP),April,2009,81100,691,776,747,AGRA,UP,2009-04-01,78.00807,27.17667
130,AGRA(UP),April,2010,106690,714,822,779,AGRA,UP,2010-04-01,78.00807,27.17667
131,AGRA(UP),April,2011,47870,631,705,673,AGRA,UP,2011-04-01,78.00807,27.17667
132,AGRA(UP),April,2012,67000,615,688,650,AGRA,UP,2012-04-01,78.00807,27.17667
133,AGRA(UP),April,2013,93980,1142,1215,1176,AGRA,UP,2013-04-01,78.00807,27.17667
134,AGRA(UP),April,2014,60150,1058,1182,1147,AGRA,UP,2014-04-01,78.00807,27.17667
135,AGRA(UP),April,2015,63800,1367,1561,1506,AGRA,UP,2015-04-01,78.00807,27.17667
136,AGRA(UP),May,2005,6750,300,376,338,AGRA,UP,2005-05-01,78.00807,27.17667
137,AGRA(UP),May,2006,15315,260,298,288,AGRA,UP,2006-05-01,78.00807,27.17667
138,AGRA(UP),May,2007,24050,473,558,513,AGRA,UP,2007-05-01,78.00807,27.17667
139,AGRA(UP),May,2008,69900,300,367,328,AGRA,UP,2008-05-01,78.00807,27.17667
140,AGRA(UP),May,2009,79860,629,707,680,AGRA,UP,2009-05-01,78.00807,27.17667
141,AGRA(UP),May,2010,97650,568,705,661,AGRA,UP,2010-05-01,78.00807,27.17667
142,AGRA(UP),May,2011,90900,573,652,615,AGRA,UP,2011-05-01,78.00807,27.17667
143,AGRA(UP),May,2012,83300,566,645,608,AGRA,UP,2012-05-01,78.00807,27.17667
144,AGRA(UP),May,2013,79860,1015,1090,1055,AGRA,UP,2013-05-01,78.00807,27.17667
145,AGRA(UP),May,2014,41045,1073,1190,1156,AGRA,UP,2014-05-01,78.00807,27.17667
146,AGRA(UP),May,2015,79030,1265,1392,1346,AGRA,UP,2015-05-01,78.00807,27.17667
147,AGRA(UP),June,2005,5700,308,372,340,AGRA,UP,2005-06-01,78.00807,27.17667
148,AGRA(UP),June,2006,13450,294,343,327,AGRA,UP,2006-06-01,78.00807,27.17667
149,AGRA(UP),June,2007,14535,520,602,563,AGRA,UP,2007-06-01,78.00807,27.17667
150,AGRA(UP),June,2008,87860,313,365,341,AGRA,UP,2008-06-01,78.00807,27.17667
151,AGRA(UP),June,2009,105372,552,642,609,AGRA,UP,2009-06-01,78.00807,27.17667
152,AGRA(UP),June,2010,86710,626,714,680,AGRA,UP,2010-06-01,78.00807,27.17667
153,AGRA(UP),June,2011,72450,507,619,562,AGRA,UP,2011-06-01,78.00807,27.17667
154,AGRA(UP),June,2012,48340,541,620,583,AGRA,UP,2012-06-01,78.00807,27.17667
155,AGRA(UP),June,2013,71440,1005,1080,1047,AGRA,UP,2013-06-01,78.00807,27.17667
156,AGRA(UP),June,2014,36960,1068,1206,1172,AGRA,UP,2014-06-01,78.00807,27.17667
157,AGRA(UP),June,2015,89880,1432,1666,1623,AGRA,UP,2015-06-01,78.00807,27.17667
158,AGRA(UP),July,2005,2300,317,383,350,AGRA,UP,2005-07-01,78.00807,27.17667
159,AGRA(UP),July,2006,12350,365,413,396,AGRA,UP,2006-07-01,78.00807,27.17667
160,AGRA(UP),July,2007,15700,915,1023,962,AGRA,UP,2007-07-01,78.00807,27.17667
161,AGRA(UP),July,2008,58290,444,555,495,AGRA,UP,2008-07-01,78.00807,27.17667
162,AGRA(UP),July,2009,78750,639,748,679,AGRA,UP,2009-07-01,78.00807,27.17667
163,AGRA(UP),July,2010,72110,772,888,846,AGRA,UP,2010-07-01,78.00807,27.17667
164,AGRA(UP),July,2011,46270,751,851,808,AGRA,UP,2011-07-01,78.00807,27.17667
165,AGRA(UP),July,2012,70690,666,754,716,AGRA,UP,2012-07-01,78.00807,27.17667
166,AGRA(UP),July,2013,36280,1601,1716,1652,AGRA,UP,2013-07-01,78.00807,27.17667
167,AGRA(UP),July,2014,22490,1677,1888,1846,AGRA,UP,2014-07-01,78.00807,27.17667
168,AGRA(UP),July,2015,65450,1979,2364,2275,AGRA,UP,2015-07-01,78.00807,27.17667
169,AGRA(UP),August,2005,3800,450,550,501,AGRA,UP,2005-08-01,78.00807,27.17667
170,AGRA(UP),August,2006,11400,381,437,420,AGRA,UP,2006-08-01,78.00807,27.17667
171,AGRA(UP),August,2007,18700,1077,1186,1132,AGRA,UP,2007-08-01,78.00807,27.17667
172,AGRA(UP),August,2008,20300,622,768,719,AGRA,UP,2008-08-01,78.00807,27.17667
173,AGRA(UP),August,2009,39180,734,831,783,AGRA,UP,2009-08-01,78.00807,27.17667
174,AGRA(UP),August,2010,67390,818,942,891,AGRA,UP,2010-08-01,78.00807,27.17667
175,AGRA(UP),August,2011,33400,947,1047,1003,AGRA,UP,2011-08-01,78.00807,27.17667
176,AGRA(UP),August,2012,71320,722,821,775,AGRA,UP,2012-08-01,78.00807,27.17667
177,AGRA(UP),August,2013,18270,3225,3513,3365,AGRA,UP,2013-08-01,78.00807,27.17667
178,AGRA(UP),August,2014,45420,1625,1862,1802,AGRA,UP,2014-08-01,78.00807,27.17667
179,AGRA(UP),August,2015,39030,2948,3464,3283,AGRA,UP,2015-08-01,78.00807,27.17667
180,AGRA(UP),September,2005,8305,847,939,894,AGRA,UP,2005-09-01,78.00807,27.17667
181,AGRA(UP),September,2006,13650,458,515,496,AGRA,UP,2006-09-01,78.00807,27.17667
182,AGRA(UP),September,2007,16650,1331,1432,1384,AGRA,UP,2007-09-01,78.00807,27.17667
183,AGRA(UP),September,2008,36930,653,925,843,AGRA,UP,2008-09-01,78.00807,27.17667
184,AGRA(UP),September,2009,35706,810,901,851,AGRA,UP,2009-09-01,78.00807,27.17667
185,AGRA(UP),September,2010,43055,1147,1272,1213,AGRA,UP,2010-09-01,78.00807,27.17667
186,AGRA(UP),September,2011,20200,1240,1394,1331,AGRA,UP,2011-09-01,78.00807,27.17667
187,AGRA(UP),September,2012,65360,726,808,766,AGRA,UP,2012-09-01,78.00807,27.17667
188,AGRA(UP),September,2013,30740,4098,4357,4225,AGRA,UP,2013-09-01,78.00807,27.17667
189,AGRA(UP),September,2014,46042,1539,1770,1675,AGRA,UP,2014-09-01,78.00807,27.17667
190,AGRA(UP),September,2015,31830,3500,4468,4318,AGRA,UP,2015-09-01,78.00807,27.17667
191,AGRA(UP),October,2005,3650,1225,1325,1267,AGRA,UP,2005-10-01,78.00807,27.17667
192,AGRA(UP),October,2006,7555,498,557,534,AGRA,UP,2006-10-01,78.00807,27.17667
193,AGRA(UP),October,2007,19312,1330,1519,1405,AGRA,UP,2007-10-01,78.00807,27.17667
194,AGRA(UP),October,2008,35165,775,891,847,AGRA,UP,2008-10-01,78.00807,27.17667
195,AGRA(UP),October,2009,29050,1198,1343,1272,AGRA,UP,2009-10-01,78.00807,27.17667
196,AGRA(UP),October,2010,38920,1327,1492,1411,AGRA,UP,2010-10-01,78.00807,27.17667
197,AGRA(UP),October,2011,30720,1330,1433,1381,AGRA,UP,2011-10-01,78.00807,27.17667
198,AGRA(UP),October,2012,51748,781,874,827,AGRA,UP,2012-10-01,78.00807,27.17667
199,AGRA(UP),October,2013,31800,4020,4384,4280,AGRA,UP,2013-10-01,78.00807,27.17667
200,AGRA(UP),October,2014,43910,1641,1838,1775,AGRA,UP,2014-10-01,78.00807,27.17667
201,AGRA(UP),October,2015,63215,2933,3844,3642,AGRA,UP,2015-10-01,78.00807,27.17667
202,AGRA(UP),November,2005,4645,1047,1175,1119,AGRA,UP,2005-11-01,78.00807,27.17667
203,AGRA(UP),November,2006,11050,465,528,511,AGRA,UP,2006-11-01,78.00807,27.17667
204,AGRA(UP),November,2007,25350,973,1116,1035,AGRA,UP,2007-11-01,78.00807,27.17667
205,AGRA(UP),November,2008,42750,867,1008,963,AGRA,UP,2008-11-01,78.00807,27.17667
206,AGRA(UP),November,2009,37750,1220,1424,1316,AGRA,UP,2009-11-01,78.00807,27.17667
207,AGRA(UP),November,2010,38705,1543,1674,1616,AGRA,UP,2010-11-01,78.00807,27.17667
208,AGRA(UP),November,2011,44660,971,1105,1042,AGRA,UP,2011-11-01,78.00807,27.17667
209,AGRA(UP),November,2012,36750,1029,1137,1085,AGRA,UP,2012-11-01,78.00807,27.17667
210,AGRA(UP),November,2013,30120,3489,3718,3631,AGRA,UP,2013-11-01,78.00807,27.17667
211,AGRA(UP),November,2014,63021,1520,1789,1675,AGRA,UP,2014-11-01,78.00807,27.17667
212,AGRA(UP),November,2015,67530,2527,2960,2832,AGRA,UP,2015-11-01,78.00807,27.17667
213,AGRA(UP),December,2005,13475,688,829,760,AGRA,UP,2005-12-01,78.00807,27.17667
214,AGRA(UP),December,2006,10300,497,565,534,AGRA,UP,2006-12-01,78.00807,27.17667
215,AGRA(UP),December,2007,46785,675,776,728,AGRA,UP,2007-12-01,78.00807,27.17667
216,AGRA(UP),December,2008,34400,1011,1140,1089,AGRA,UP,2008-12-01,78.00807,27.17667
217,AGRA(UP),December,2009,43500,1170,1320,1242,AGRA,UP,2009-12-01,78.00807,27.17667
218,AGRA(UP),December,2010,40465,2097,2377,2283,AGRA,UP,2010-12-01,78.00807,27.17667
219,AGRA(UP),December,2011,47490,725,827,788,AGRA,UP,2011-12-01,78.00807,27.17667
220,AGRA(UP),December,2012,44380,1223,1320,1274,AGRA,UP,2012-12-01,78.00807,27.17667
221,AGRA(UP),December,2013,63600,1748,1943,1878,AGRA,UP,2013-12-01,78.00807,27.17667
222,AGRA(UP),December,2014,74750,1450,1720,1623,AGRA,UP,2014-12-01,78.00807,27.17667
223,AGRA(UP),December,2015,106360,1486,1953,1857,AGRA,UP,2015-12-01,78.00807,27.17667
224,AHMEDABAD(GUJ),January,2005,41880,242,416,332,AHMEDABAD,GUJ,2005-01-01,72.57136,23.02250
225,AHMEDABAD(GUJ),January,2006,24540,290,485,386,AHMEDABAD,GUJ,2006-01-01,72.57136,23.02250
226,AHMEDABAD(GUJ),January,2008,97428,332,482,415,AHMEDABAD,GUJ,2008-01-01,72.57136,23.02250
227,AHMEDABAD(GUJ),January,2009,77050,1031,1507,1250,AHMEDABAD,GUJ,2009-01-01,72.57136,23.02250
228,AHMEDABAD(GUJ),January,2010,134394,796,1462,1202,AHMEDABAD,GUJ,2010-01-01,72.57136,23.02250
229,AHMEDABAD(GUJ),January,2011,73739,1407,3243,2550,AHMEDABAD,GUJ,2011-01-01,72.57136,23.02250
230,AHMEDABAD(GUJ),January,2012,111346,298,641,520,AHMEDABAD,GUJ,2012-01-01,72.57136,23.02250
231,AHMEDABAD(GUJ),January,2013,112855,1150,1740,1490,AHMEDABAD,GUJ,2013-01-01,72.57136,23.02250
232,AHMEDABAD(GUJ),January,2014,125617,773,1446,1233,AHMEDABAD,GUJ,2014-01-01,72.57136,23.02250
233,AHMEDABAD(GUJ),January,2015,137027,829,1358,1158,AHMEDABAD,GUJ,2015-01-01,72.57136,23.02250
234,AHMEDABAD(GUJ),January,2016,198390,646,1224,997,AHMEDABAD,GUJ,2016-01-01,72.57136,23.02250
235,AHMEDABAD(GUJ),February,2005,80837,166,386,281,AHMEDABAD,GUJ,2005-02-01,72.57136,23.02250
236,AHMEDABAD(GUJ),February,2006,41310,153,359,253,AHMEDABAD,GUJ,2006-02-01,72.57136,23.02250
237,AHMEDABAD(GUJ),February,2008,66012,297,431,375,AHMEDABAD,GUJ,2008-02-01,72.57136,23.02250
238,AHMEDABAD(GUJ),February,2009,54451,821,1325,1060,AHMEDABAD,GUJ,2009-02-01,72.57136,23.02250
239,AHMEDABAD(GUJ),February,2010,127030,763,1209,1060,AHMEDABAD,GUJ,2010-02-01,72.57136,23.02250

The data contains 12 parameters pread across 10320 observations.

The prices of onion can be categorised on the basis of location (states in India) and the variations can be seen over time to identify any patterns in the prices based on the month of the year. It can be assumed that the prices depend on the following factors:
* Production in an area
* Import
* Export

First, let us look at price variations by month and year in the different states.

In [41]:
onion_year = onion_df.sort_values(by=['date','state','city'], ascending=[1,1,1]);
# sorting the data based on the Date, City and State
onion_year.to_csv('../onion/data/onion_trimmed.csv')
onion_year

,market,month,year,quantity,priceMin,priceMax,priceMod,city,state,date,lon,lat
5453,LASALGAON(MS),January,1996,225063,160,257,226,LASALGAON,MS,1996-01-01,74.23261,20.14914
5474,LASALGAON(MS),February,1996,196164,133,229,186,LASALGAON,MS,1996-02-01,74.23261,20.14914
5495,LASALGAON(MS),March,1996,178992,155,274,243,LASALGAON,MS,1996-03-01,74.23261,20.14914
5516,LASALGAON(MS),April,1996,192592,136,279,254,LASALGAON,MS,1996-04-01,74.23261,20.14914
5536,LASALGAON(MS),May,1996,237574,154,312,269,LASALGAON,MS,1996-05-01,74.23261,20.14914
5556,LASALGAON(MS),June,1996,175308,229,413,367,LASALGAON,MS,1996-06-01,74.23261,20.14914
5576,LASALGAON(MS),July,1996,156282,229,406,368,LASALGAON,MS,1996-07-01,74.23261,20.14914
5596,LASALGAON(MS),August,1996,173892,164,388,340,LASALGAON,MS,1996-08-01,74.23261,20.14914
5616,LASALGAON(MS),September,1996,138648,145,363,317,LASALGAON,MS,1996-09-01,74.23261,20.14914
5636,LASALGAON(MS),October,1996,149113,160,560,492,LASALGAON,MS,1996-10-01,74.23261,20.14914
5656,LASALGAON(MS),November,1996,96295,138,498,376,LASALGAON,MS,1996-11-01,74.23261,20.14914
5676,LASALGAON(MS),December,1996,240615,138,451,385,LASALGAON,MS,1996-12-01,74.23261,20.14914
5454,LASALGAON(MS),January,1997,241225,126,323,290,LASALGAON,MS,1997-01-01,74.23261,20.14914
5475,LASALGAON(MS),February,1997,229550,134,305,271,LASALGAON,MS,1997-02-01,74.23261,20.14914
5496,LASALGAON(MS),March,1997,130885,138,310,273,LASALGAON,MS,1997-03-01,74.23261,20.14914
5517,LASALGAON(MS),April,1997,223608,149,240,214,LASALGAON,MS,1997-04-01,74.23261,20.14914
5537,LASALGAON(MS),May,1997,251132,123,238,213,LASALGAON,MS,1997-05-01,74.23261,20.14914
5557,LASALGAON(MS),June,1997,138178,64,237,195,LASALGAON,MS,1997-06-01,74.23261,20.14914
5577,LASALGAON(MS),July,1997,235057,37,225,168,LASALGAON,MS,1997-07-01,74.23261,20.14914
7258,NIPHAD(MS),July,1997,25587,47,161,133,NIPHAD,MS,1997-07-01,74.10931,20.07996
7756,PIMPALGAON(MS),July,1997,174521,92,225,151,PIMPALGAON,MS,1997-07-01,73.98738,20.16997
8779,SAIKHEDA(MS),July,1997,36918,80,193,168,SAIKHEDA,MS,1997-07-01,78.58312,22.96222
9394,SINNAR(MS),July,1997,38022,34,161,121,SINNAR,MS,1997-07-01,74.00063,19.85306
5597,LASALGAON(MS),August,1997,235143,43,257,210,LASALGAON,MS,1997-08-01,74.23261,20.14914
7276,NIPHAD(MS),August,1997,17456,78,230,197,NIPHAD,MS,1997-08-01,74.10931,20.07996
7775,PIMPALGAON(MS),August,1997,143686,121,256,201,PIMPALGAON,MS,1997-08-01,73.98738,20.16997
8792,SAIKHEDA(MS),August,1997,38850,95,219,194,SAIKHEDA,MS,1997-08-01,78.58312,22.96222
9411,SINNAR(MS),August,1997,34032,21,215,173,SINNAR,MS,1997-08-01,74.00063,19.85306
5617,LASALGAON(MS),September,1997,252960,35,318,241,LASALGAON,MS,1997-09-01,74.23261,20.14914
7294,NIPHAD(MS),September,1997,14054,108,274,234,NIPHAD,MS,1997-09-01,74.10931,20.07996
7794,PIMPALGAON(MS),September,1997,194398,136,313,260,PIMPALGAON,MS,1997-09-01,73.98738,20.16997
8804,SAIKHEDA(MS),September,1997,27000,97,270,238,SAIKHEDA,MS,1997-09-01,78.58312,22.96222
9427,SINNAR(MS),September,1997,29613,16,271,230,SINNAR,MS,1997-09-01,74.00063,19.85306
5637,LASALGAON(MS),October,1997,208213,45,412,331,LASALGAON,MS,1997-10-01,74.23261,20.14914
7311,NIPHAD(MS),October,1997,7170,123,389,318,NIPHAD,MS,1997-10-01,74.10931,20.07996
7813,PIMPALGAON(MS),October,1997,103984,251,413,345,PIMPALGAON,MS,1997-10-01,73.98738,20.16997
8820,SAIKHEDA(MS),October,1997,23148,129,376,315,SAIKHEDA,MS,1997-10-01,78.58312,22.96222
9445,SINNAR(MS),October,1997,17345,31,352,301,SINNAR,MS,1997-10-01,74.00063,19.85306
5657,LASALGAON(MS),November,1997,145358,117,852,711,LASALGAON,MS,1997-11-01,74.23261,20.14914
7328,NIPHAD(MS),November,1997,1965,243,720,638,NIPHAD,MS,1997-11-01,74.10931,20.07996
7832,PIMPALGAON(MS),November,1997,123900,383,861,655,PIMPALGAON,MS,1997-11-01,73.98738,20.16997
8836,SAIKHEDA(MS),November,1997,6468,240,641,587,SAIKHEDA,MS,1997-11-01,78.58312,22.96222
9463,SINNAR(MS),November,1997,6733,74,634,496,SINNAR,MS,1997-11-01,74.00063,19.85306
5677,LASALGAON(MS),December,1997,106968,118,1144,837,LASALGAON,MS,1997-12-01,74.23261,20.14914
7851,PIMPALGAON(MS),December,1997,113545,415,1255,881,PIMPALGAON,MS,1997-12-01,73.98738,20.16997
8850,SAIKHEDA(MS),December,1997,1320,92,559,329,SAIKHEDA,MS,1997-12-01,78.58312,22.96222
9481,SINNAR(MS),December,1997,12228,143,1003,708,SINNAR,MS,1997-12-01,74.00063,19.85306
1591,CHAKAN(MS),January,1998,4615,333,1633,975,CHAKAN,MS,1998-01-01,73.86303,18.76027
5455,LASALGAON(MS),January,1998,125731,225,1447,1037,LASALGAON,MS,1998-01-01,74.23261,20.14914
5696,LONAND(MS),January,1998,9800,910,1640,1340,LONAND,MS,1998-01-01,74.18618,18.04171
6493,MANMAD(MS),January,1998,48360,375,1361,972,MANMAD,MS,1998-01-01,74.43660,20.25118
7645,PIMPALGAON(MS),January,1998,112597,607,1594,1140,PIMPALGAON,MS,1998-01-01,73.98738,20.16997
8691,SAIKHEDA(MS),January,1998,7656,364,1488,802,SAIKHEDA,MS,1998-01-01,78.58312,22.96222
9292,SINNAR(MS),January,1998,35418,223,1538,1081,SINNAR,MS,1998-01-01,74.00063,19.85306
1605,CHAKAN(MS),February,1998,26300,175,1142,775,CHAKAN,MS,1998-02-01,73.86303,18.76027
5476,LASALGAON(MS),February,1998,152960,267,1126,920,LASALGAON,MS,1998-02-01,74.23261,20.14914
5714,LONAND(MS),February,1998,16250,438,1053,731,LONAND,MS,1998-02-01,74.18618,18.04171
6512,MANMAD(MS),February,1998,63165,351,1048,828,MANMAD,MS,1998-02-01,74.43660,20.25118
7173,NIPHAD(MS),February,1998,3531,163,878,750,NIPHAD,MS,1998-02-01,74.10931,20.07996
7664,PIMPALGAON(MS),February,1998,186566,581,1151,919,PIMPALGAON,MS,1998-02-01,73.98738,20.16997
8706,SAIKHEDA(MS),February,1998,15704,472,1024,765,SAIKHEDA,MS,1998-02-01,78.58312,22.96222
9310,SINNAR(MS),February,1998,58060,221,1076,888,SINNAR,MS,1998-02-01,74.00063,19.85306
1152,BHAVNAGAR(GUJ),March,1998,190900,309,459,423,BHAVNAGAR,GUJ,1998-03-01,72.15193,21.76447
1617,CHAKAN(MS),March,1998,130900,184,419,331,CHAKAN,MS,1998-03-01,73.86303,18.76027
5497,LASALGAON(MS),March,1998,281027,152,486,417,LASALGAON,MS,1998-03-01,74.23261,20.14914
5733,LONAND(MS),March,1998,75000,293,397,355,LONAND,MS,1998-03-01,74.18618,18.04171
6531,MANMAD(MS),March,1998,129141,231,510,405,MANMAD,MS,1998-03-01,74.43660,20.25118
7190,NIPHAD(MS),March,1998,11450,163,507,463,NIPHAD,MS,1998-03-01,74.10931,20.07996
7683,PIMPALGAON(MS),March,1998,249063,326,535,454,PIMPALGAON,MS,1998-03-01,73.98738,20.16997
8723,SAIKHEDA(MS),March,1998,25545,303,474,387,SAIKHEDA,MS,1998-03-01,78.58312,22.96222
9328,SINNAR(MS),March,1998,40010,74,414,359,SINNAR,MS,1998-03-01,74.00063,19.85306
1169,BHAVNAGAR(GUJ),April,1998,92000,187,299,260,BHAVNAGAR,GUJ,1998-04-01,72.15193,21.76447
6171,MAHUVA(GUJ),April,1998,251800,181,299,256,MAHUVA,GUJ,1998-04-01,71.75632,21.09022
1630,CHAKAN(MS),April,1998,36750,199,281,253,CHAKAN,MS,1998-04-01,73.86303,18.76027
5518,LASALGAON(MS),April,1998,119035,76,318,258,LASALGAON,MS,1998-04-01,74.23261,20.14914
5752,LONAND(MS),April,1998,25000,255,290,265,LONAND,MS,1998-04-01,74.18618,18.04171
6550,MANMAD(MS),April,1998,50600,142,275,217,MANMAD,MS,1998-04-01,74.43660,20.25118
7207,NIPHAD(MS),April,1998,3900,67,304,237,NIPHAD,MS,1998-04-01,74.10931,20.07996
7702,PIMPALGAON(MS),April,1998,36792,166,316,235,PIMPALGAON,MS,1998-04-01,73.98738,20.16997
8738,SAIKHEDA(MS),April,1998,13190,156,269,225,SAIKHEDA,MS,1998-04-01,78.58312,22.96222
9346,SINNAR(MS),April,1998,11150,38,272,227,SINNAR,MS,1998-04-01,74.00063,19.85306
1185,BHAVNAGAR(GUJ),May,1998,2500,150,325,200,BHAVNAGAR,GUJ,1998-05-01,72.15193,21.76447
6188,MAHUVA(GUJ),May,1998,99975,199,331,268,MAHUVA,GUJ,1998-05-01,71.75632,21.09022
1643,CHAKAN(MS),May,1998,19785,208,382,337,CHAKAN,MS,1998-05-01,73.86303,18.76027
5538,LASALGAON(MS),May,1998,233819,97,381,321,LASALGAON,MS,1998-05-01,74.23261,20.14914
5770,LONAND(MS),May,1998,5000,325,406,375,LONAND,MS,1998-05-01,74.18618,18.04171
6568,MANMAD(MS),May,1998,60430,181,318,278,MANMAD,MS,1998-05-01,74.43660,20.25118
7224,NIPHAD(MS),May,1998,32315,135,340,298,NIPHAD,MS,1998-05-01,74.10931,20.07996
7720,PIMPALGAON(MS),May,1998,231145,207,381,297,PIMPALGAON,MS,1998-05-01,73.98738,20.16997
8751,SAIKHEDA(MS),May,1998,32779,216,337,295,SAIKHEDA,MS,1998-05-01,78.58312,22.96222
9362,SINNAR(MS),May,1998,25018,50,343,301,SINNAR,MS,1998-05-01,74.00063,19.85306
6206,MAHUVA(GUJ),June,1998,8679,327,490,435,MAHUVA,GUJ,1998-06-01,71.75632,21.09022
1656,CHAKAN(MS),June,1998,16790,256,699,619,CHAKAN,MS,1998-06-01,73.86303,18.76027
5558,LASALGAON(MS),June,1998,272471,158,703,583,LASALGAON,MS,1998-06-01,74.23261,20.14914
5788,LONAND(MS),June,1998,860,483,607,547,LONAND,MS,1998-06-01,74.18618,18.04171
6586,MANMAD(MS),June,1998,71217,292,625,531,MANMAD,MS,1998-06-01,74.43660,20.25118
7241,NIPHAD(MS),June,1998,30774,294,610,549,NIPHAD,MS,1998-06-01,74.10931,20.07996
7738,PIMPALGAON(MS),June,1998,188485,435,682,576,PIMPALGAON,MS,1998-06-01,73.98738,20.16997
8766,SAIKHEDA(MS),June,1998,24137,346,744,637,SAIKHEDA,MS,1998-06-01,78.58312,22.96222
9378,SINNAR(MS),June,1998,25847,112,719,622,SINNAR,MS,1998-06-01,74.00063,19.85306
6224,MAHUVA(GUJ),July,1998,13885,453,805,751,MAHUVA,GUJ,1998-07-01,71.75632,21.09022
1667,CHAKAN(MS),July,1998,17200,439,950,876,CHAKAN,MS,1998-07-01,73.86303,18.76027
5578,LASALGAON(MS),July,1998,158223,263,932,844,LASALGAON,MS,1998-07-01,74.23261,20.14914
5806,LONAND(MS),July,1998,425,680,870,775,LONAND,MS,1998-07-01,74.18618,18.04171
6604,MANMAD(MS),July,1998,25923,588,896,833,MANMAD,MS,1998-07-01,74.43660,20.25118
7259,NIPHAD(MS),July,1998,11525,590,897,840,NIPHAD,MS,1998-07-01,74.10931,20.07996
7757,PIMPALGAON(MS),July,1998,100632,691,935,870,PIMPALGAON,MS,1998-07-01,73.98738,20.16997
8780,SAIKHEDA(MS),July,1998,12236,549,881,833,SAIKHEDA,MS,1998-07-01,78.58312,22.96222
9395,SINNAR(MS),July,1998,17898,330,907,840,SINNAR,MS,1998-07-01,74.00063,19.85306
6242,MAHUVA(GUJ),August,1998,4190,743,1342,1032,MAHUVA,GUJ,1998-08-01,71.75632,21.09022
1678,CHAKAN(MS),August,1998,8500,459,1603,1444,CHAKAN,MS,1998-08-01,73.86303,18.76027
5598,LASALGAON(MS),August,1998,112556,332,1459,1343,LASALGAON,MS,1998-08-01,74.23261,20.14914
5822,LONAND(MS),August,1998,650,667,1250,1083,LONAND,MS,1998-08-01,74.18618,18.04171
6622,MANMAD(MS),August,1998,19657,738,1427,1344,MANMAD,MS,1998-08-01,74.43660,20.25118
7277,NIPHAD(MS),August,1998,15677,953,1460,1373,NIPHAD,MS,1998-08-01,74.10931,20.07996
7776,PIMPALGAON(MS),August,1998,91603,1129,1468,1385,PIMPALGAON,MS,1998-08-01,73.98738,20.16997
8793,SAIKHEDA(MS),August,1998,7676,1029,1485,1267,SAIKHEDA,MS,1998-08-01,78.58312,22.96222
9412,SINNAR(MS),August,1998,17512,215,1463,1317,SINNAR,MS,1998-08-01,74.00063,19.85306
6259,MAHUVA(GUJ),September,1998,1948,888,1594,1334,MAHUVA,GUJ,1998-09-01,71.75632,21.09022
1692,CHAKAN(MS),September,1998,3350,1017,2042,1850,CHAKAN,MS,1998-09-01,73.86303,18.76027
5618,LASALGAON(MS),September,1998,100767,386,2001,1908,LASALGAON,MS,1998-09-01,74.23261,20.14914
5838,LONAND(MS),September,1998,1350,1267,1583,1400,LONAND,MS,1998-09-01,74.18618,18.04171
6640,MANMAD(MS),September,1998,9212,1219,1792,1684,MANMAD,MS,1998-09-01,74.43660,20.25118
7295,NIPHAD(MS),September,1998,13485,1045,2038,1935,NIPHAD,MS,1998-09-01,74.10931,20.07996
7795,PIMPALGAON(MS),September,1998,79488,1610,1952,1862,PIMPALGAON,MS,1998-09-01,73.98738,20.16997
8805,SAIKHEDA(MS),September,1998,3325,1303,1864,1761,SAIKHEDA,MS,1998-09-01,78.58312,22.96222
9428,SINNAR(MS),September,1998,8250,396,2024,1779,SINNAR,MS,1998-09-01,74.00063,19.85306
1200,BHAVNAGAR(GUJ),October,1998,150,1000,2250,1250,BHAVNAGAR,GUJ,1998-10-01,72.15193,21.76447
6276,MAHUVA(GUJ),October,1998,1128,1233,1996,1607,MAHUVA,GUJ,1998-10-01,71.75632,21.09022
1705,CHAKAN(MS),October,1998,518,1050,2463,1725,CHAKAN,MS,1998-10-01,73.86303,18.76027
5638,LASALGAON(MS),October,1998,40024,500,2954,2632,LASALGAON,MS,1998-10-01,74.23261,20.14914
5856,LONAND(MS),October,1998,2250,1400,2533,1833,LONAND,MS,1998-10-01,74.18618,18.04171
6658,MANMAD(MS),October,1998,1570,800,2638,2069,MANMAD,MS,1998-10-01,74.43660,20.25118
7312,NIPHAD(MS),October,1998,4261,1113,3365,3027,NIPHAD,MS,1998-10-01,74.10931,20.07996
7814,PIMPALGAON(MS),October,1998,14571,2197,3051,2754,PIMPALGAON,MS,1998-10-01,73.98738,20.16997
8821,SAIKHEDA(MS),October,1998,266,1900,2925,2398,SAIKHEDA,MS,1998-10-01,78.58312,22.96222
9446,SINNAR(MS),October,1998,530,288,2863,1874,SINNAR,MS,1998-10-01,74.00063,19.85306
1203,BHAVNAGAR(GUJ),November,1998,300,1500,1900,1700,BHAVNAGAR,GUJ,1998-11-01,72.15193,21.76447
6293,MAHUVA(GUJ),November,1998,5125,693,1452,1135,MAHUVA,GUJ,1998-11-01,71.75632,21.09022
1717,CHAKAN(MS),November,1998,740,500,1779,1133,CHAKAN,MS,1998-11-01,73.86303,18.76027
5658,LASALGAON(MS),November,1998,49798,245,2080,1689,LASALGAON,MS,1998-11-01,74.23261,20.14914
5873,LONAND(MS),November,1998,10500,1275,1988,1638,LONAND,MS,1998-11-01,74.18618,18.04171
6676,MANMAD(MS),November,1998,9300,890,1708,1452,MANMAD,MS,1998-11-01,74.43660,20.25118
7833,PIMPALGAON(MS),November,1998,61590,892,2061,1513,PIMPALGAON,MS,1998-11-01,73.98738,20.16997
9464,SINNAR(MS),November,1998,825,150,1697,1233,SINNAR,MS,1998-11-01,74.00063,19.85306
1214,BHAVNAGAR(GUJ),December,1998,75770,883,1168,1041,BHAVNAGAR,GUJ,1998-12-01,72.15193,21.76447
6310,MAHUVA(GUJ),December,1998,35903,788,1132,982,MAHUVA,GUJ,1998-12-01,71.75632,21.09022
1730,CHAKAN(MS),December,1998,2237,344,1385,925,CHAKAN,MS,1998-12-01,73.86303,18.76027
5678,LASALGAON(MS),December,1998,153905,442,1152,1069,LASALGAON,MS,1998-12-01,74.23261,20.14914
5890,LONAND(MS),December,1998,12000,925,1375,1200,LONAND,MS,1998-12-01,74.18618,18.04171
6694,MANMAD(MS),December,1998,88400,767,1162,1055,MANMAD,MS,1998-12-01,74.43660,20.25118
7852,PIMPALGAON(MS),December,1998,172317,847,1180,1069,PIMPALGAON,MS,1998-12-01,73.98738,20.16997
9482,SINNAR(MS),December,1998,15600,219,1219,1013,SINNAR,MS,1998-12-01,74.00063,19.85306
1120,BHAVNAGAR(GUJ),January,1999,393650,447,523,486,BHAVNAGAR,GUJ,1999-01-01,72.15193,21.76447
6117,MAHUVA(GUJ),January,1999,73760,393,553,477,MAHUVA,GUJ,1999-01-01,71.75632,21.09022
1592,CHAKAN(MS),January,1999,8900,157,681,479,CHAKAN,MS,1999-01-01,73.86303,18.76027
5456,LASALGAON(MS),January,1999,236001,310,545,498,LASALGAON,MS,1999-01-01,74.23261,20.14914
5697,LONAND(MS),January,1999,12000,333,617,502,LONAND,MS,1999-01-01,74.18618,18.04171
6494,MANMAD(MS),January,1999,93800,449,562,519,MANMAD,MS,1999-01-01,74.43660,20.25118
7646,PIMPALGAON(MS),January,1999,197678,411,558,501,PIMPALGAON,MS,1999-01-01,73.98738,20.16997
7870,PUNE(MS),January,1999,261782,313,648,502,PUNE,MS,1999-01-01,73.85674,18.52043
9293,SINNAR(MS),January,1999,50788,175,524,462,SINNAR,MS,1999-01-01,74.00063,19.85306
1136,BHAVNAGAR(GUJ),February,1999,401750,276,332,308,BHAVNAGAR,GUJ,1999-02-01,72.15193,21.76447
6135,MAHUVA(GUJ),February,1999,208000,249,333,298,MAHUVA,GUJ,1999-02-01,71.75632,21.09022
1606,CHAKAN(MS),February,1999,50400,200,361,287,CHAKAN,MS,1999-02-01,73.86303,18.76027
5477,LASALGAON(MS),February,1999,154785,140,347,271,LASALGAON,MS,1999-02-01,74.23261,20.14914
5715,LONAND(MS),February,1999,25500,144,284,243,LONAND,MS,1999-02-01,74.18618,18.04171
6513,MANMAD(MS),February,1999,77500,209,304,268,MANMAD,MS,1999-02-01,74.43660,20.25118
7174,NIPHAD(MS),February,1999,21489,185,353,314,NIPHAD,MS,1999-02-01,74.10931,20.07996
7665,PIMPALGAON(MS),February,1999,165305,250,360,302,PIMPALGAON,MS,1999-02-01,73.98738,20.16997
7888,PUNE(MS),February,1999,348353,238,379,321,PUNE,MS,1999-02-01,73.85674,18.52043
8707,SAIKHEDA(MS),February,1999,17682,186,304,256,SAIKHEDA,MS,1999-02-01,78.58312,22.96222
9311,SINNAR(MS),February,1999,30400,107,278,246,SINNAR,MS,1999-02-01,74.00063,19.85306
1153,BHAVNAGAR(GUJ),March,1999,317500,225,304,270,BHAVNAGAR,GUJ,1999-03-01,72.15193,21.76447
6153,MAHUVA(GUJ),March,1999,187500,210,317,267,MAHUVA,GUJ,1999-03-01,71.75632,21.09022
1618,CHAKAN(MS),March,1999,32250,188,338,278,CHAKAN,MS,1999-03-01,73.86303,18.76027
5498,LASALGAON(MS),March,1999,228760,110,292,233,LASALGAON,MS,1999-03-01,74.23261,20.14914
5734,LONAND(MS),March,1999,23000,217,292,260,LONAND,MS,1999-03-01,74.18618,18.04171
6532,MANMAD(MS),March,1999,89650,134,258,218,MANMAD,MS,1999-03-01,74.43660,20.25118
7191,NIPHAD(MS),March,1999,26656,125,264,230,NIPHAD,MS,1999-03-01,74.10931,20.07996
7684,PIMPALGAON(MS),March,1999,151993,162,265,214,PIMPALGAON,MS,1999-03-01,73.98738,20.16997
7906,PUNE(MS),March,1999,353155,245,333,292,PUNE,MS,1999-03-01,73.85674,18.52043
8724,SAIKHEDA(MS),March,1999,9026,157,274,236,SAIKHEDA,MS,1999-03-01,78.58312,22.96222
9329,SINNAR(MS),March,1999,22500,57,254,216,SINNAR,MS,1999-03-01,74.00063,19.85306
1170,BHAVNAGAR(GUJ),April,1999,306150,230,358,314,BHAVNAGAR,GUJ,1999-04-01,72.15193,21.76447
6172,MAHUVA(GUJ),April,1999,512000,220,370,328,MAHUVA,GUJ,1999-04-01,71.75632,21.09022
1631,CHAKAN(MS),April,1999,33250,243,440,376,CHAKAN,MS,1999-04-01,73.86303,18.76027
5519,LASALGAON(MS),April,1999,130225,119,468,358,LASALGAON,MS,1999-04-01,74.23261,20.14914
5753,LONAND(MS),April,1999,46100,232,381,330,LONAND,MS,1999-04-01,74.18618,18.04171
6551,MANMAD(MS),April,1999,23570,146,391,296,MANMAD,MS,1999-04-01,74.43660,20.25118
7208,NIPHAD(MS),April,1999,11979,149,453,353,NIPHAD,MS,1999-04-01,74.10931,20.07996
7703,PIMPALGAON(MS),April,1999,118147,218,464,361,PIMPALGAON,MS,1999-04-01,73.98738,20.16997
7924,PUNE(MS),April,1999,390826,252,400,354,PUNE,MS,1999-04-01,73.85674,18.52043
8739,SAIKHEDA(MS),April,1999,12358,181,407,351,SAIKHEDA,MS,1999-04-01,78.58312,22.96222
9347,SINNAR(MS),April,1999,34554,51,407,333,SINNAR,MS,1999-04-01,74.00063,19.85306
1186,BHAVNAGAR(GUJ),May,1999,10500,350,425,390,BHAVNAGAR,GUJ,1999-05-01,72.15193,21.76447
6189,MAHUVA(GUJ),May,1999,241000,218,451,392,MAHUVA,GUJ,1999-05-01,71.75632,21.09022
1644,CHAKAN(MS),May,1999,28527,200,586,434,CHAKAN,MS,1999-05-01,73.86303,18.76027
5539,LASALGAON(MS),May,1999,199710,180,648,533,LASALGAON,MS,1999-05-01,74.23261,20.14914
5771,LONAND(MS),May,1999,11032,250,521,433,LONAND,MS,1999-05-01,74.18618,18.04171
6569,MANMAD(MS),May,1999,55100,143,537,465,MANMAD,MS,1999-05-01,74.43660,20.25118
7225,NIPHAD(MS),May,1999,36930,160,599,450,NIPHAD,MS,1999-05-01,74.10931,20.07996
7721,PIMPALGAON(MS),May,1999,283161,334,616,493,PIMPALGAON,MS,1999-05-01,73.98738,20.16997
7941,PUNE(MS),May,1999,403277,317,555,489,PUNE,MS,1999-05-01,73.85674,18.52043
8752,SAIKHEDA(MS),May,1999,23816,232,514,457,SAIKHEDA,MS,1999-05-01,78.58312,22.96222
9363,SINNAR(MS),May,1999,34706,96,547,430,SINNAR,MS,1999-05-01,74.00063,19.85306
6207,MAHUVA(GUJ),June,1999,15849,213,392,327,MAHUVA,GUJ,1999-06-01,71.75632,21.09022
1657,CHAKAN(MS),June,1999,8600,214,499,397,CHAKAN,MS,1999-06-01,73.86303,18.76027
5559,LASALGAON(MS),June,1999,179780,186,554,443,LASALGAON,MS,1999-06-01,74.23261,20.14914
5789,LONAND(MS),June,1999,2700,320,505,430,LONAND,MS,1999-06-01,74.18618,18.04171
6587,MANMAD(MS),June,1999,18950,197,485,390,MANMAD,MS,1999-06-01,74.43660,20.25118
7242,NIPHAD(MS),June,1999,32417,205,530,424,NIPHAD,MS,1999-06-01,74.10931,20.07996
7739,PIMPALGAON(MS),June,1999,157910,311,548,469,PIMPALGAON,MS,1999-06-01,73.98738,20.16997
7958,PUNE(MS),June,1999,324550,313,531,478,PUNE,MS,1999-06-01,73.85674,18.52043
8767,SAIKHEDA(MS),June,1999,14788,265,458,412,SAIKHEDA,MS,1999-06-01,78.58312,22.96222
9379,SINNAR(MS),June,1999,27090,64,477,405,SINNAR,MS,1999-06-01,74.00063,19.85306
6225,MAHUVA(GUJ),July,1999,15950,315,514,430,MAHUVA,GUJ,1999-07-01,71.75632,21.09022
1668,CHAKAN(MS),July,1999,13300,150,485,381,CHAKAN,MS,1999-07-01,73.86303,18.76027
5579,LASALGAON(MS),July,1999,180555,188,483,429,LASALGAON,MS,1999-07-01,74.23261,20.14914
5807,LONAND(MS),July,1999,559,200,461,404,LONAND,MS,1999-07-01,74.18618,18.04171
6605,MANMAD(MS),July,1999,37900,245,463,436,MANMAD,MS,1999-07-01,74.43660,20.25118
7260,NIPHAD(MS),July,1999,18805,240,493,443,NIPHAD,MS,1999-07-01,74.10931,20.07996
7758,PIMPALGAON(MS),July,1999,161917,304,501,441,PIMPALGAON,MS,1999-07-01,73.98738,20.16997
7975,PUNE(MS),July,1999,193343,302,548,450,PUNE,MS,1999-07-01,73.85674,18.52043
8781,SAIKHEDA(MS),July,1999,16346,278,459,432,SAIKHEDA,MS,1999-07-01,78.58312,22.96222

In [42]:
onion_year1 = onion_year.groupby(['state','city'])
onion_year1.count()

                     market  month  year  quantity  priceMin  priceMax  \
state city
AP    HYDERABAD         137    137   137       137       137       137
      KURNOOL           142    142   142       142       142       142
      RAJAHMUNDRY         1      1     1         1         1         1
ASM   GUWAHATI          135    135   135       135       135       135
BHR   BIHARSHARIF         2      2     2         2         2         2
      PATNA             139    139   139       139       139       139
DEL   DELHI             159    159   159       159       159       159
GUJ   AHMEDABAD         126    126   126       126       126       126
      BHAVNAGAR         110    110   110       110       110       110
      DEESA              16     16    16        16        16        16
      GONDAL            164    164   164       164       164       164
      JAMNAGAR            6      6     6         6         6         6
      MAHUVA            211    211   211       211       211       211
      RAJKOT            157    157   157       157       157       157
      SURAT             147    147   147       147       147       147
HP    SHIMLA             40     40    40        40        40        40
HR    CHANDIGARH          3      3     3         3         3         3
      KARNAL            124    124   124       124       124       124
      RAIPUR            110    110   110       110       110       110
JH    RANCHI            123    123   123       123       123       123
JK    JAMMU             135    135   135       135       135       135
      SRINAGAR           29     29    29        29        29        29
KEL   TRIVENDRUM         55     55    55        55        55        55
KER   PALAYAM            14     14    14        14        14        14
KNT   BANGALORE         147    147   147       147       147       147
      BELGAUM           147    147   147       147       147       147
      BIJAPUR           130    130   130       130       130       130
      CHALLAKERE          1      1     1         1         1         1
      CHICKBALLAPUR      12     12    12        12        12        12
      DHAVANGERE        164    164   164       164       164       164
      HASSAN            123    123   123       123       123       123
      HUBLI             174    174   174       174       174       174
      KOLAR              12     12    12        12        12        12
      RAICHUR            17     17    17        17        17        17
MH    MUMBAI            147    147   147       147       147       147
      NAGPUR            130    130   130       130       130       130
MP    BHOPAL             44     44    44        44        44        44
      DEWAS              21     21    21        21        21        21
      INDORE            166    166   166       166       166       166
      MANDSOUR           18     18    18        18        18        18
      NEEMUCH             1      1     1         1         1         1
      SAGAR              17     17    17        17        17        17
      UJJAIN             44     44    44        44        44        44
MS    AHMEDNAGAR        144    144   144       144       144       144
      BOMBORI            29     29    29        29        29        29
      CHAKAN            153    153   153       153       153       153
      CHANDVAD           17     17    17        17        17        17
      DEVALA            122    122   122       122       122       122
      DHULIA            159    159   159       159       159       159
      DINDORI            41     41    41        41        41        41
      JALGAON           133    133   133       133       133       133
      JUNNAR             98     98    98        98        98        98
      KALVAN            115    115   115       115       115       115
      KOLHAPUR          144    144   144       144       144       144
      KOPERGAON          17     17    17        17        17        17
      LASALGAON         243    243   243       243       243       243
      LONAND            212    212   212       212       212       212
      MALEGAON          147    147   147       147       147       147
      MANMAD            219    219   219       219       219       219
      NANDGAON            6      6     6         6         6         6
      NASIK             142    142   142       142       142       142
      NEWASA             17     17    17        17        17        17
      NIPHAD            201    201   201       201       201       201
      PHALTAN            14     14    14        14        14        14
      PIMPALGAON        225    225   225       225       225       225
      PUNE              207    207   207       207       207       207
      RAHATA             17     17    17        17        17        17
      RAHURI            155    155   155       155       155       155
      SAIKHEDA          172    172   172       172       172       172
      SANGALI            58     58    58        58        58        58
      SANGAMNER         110    110   110       110       110       110
      SATANA             83     83    83        83        83        83
      SHRIRAMPUR        129    129   129       129       129       129
      SINNAR            207    207   207       207       207       207
      SOLAPUR           141    141   141       141       141       141
      SRIRAMPUR           3      3     3         3         3         3
      VANI               83     83    83        83        83        83
      YEOLA             147    147   147       147       147       147
OR    BHUBNESWER        130    130   130       130       130       130
PB    ABOHAR             90     90    90        90        90        90
      AMRITSAR          122    122   122       122       122       122
      BHATINDA           86     86    86        86        86        86
      HOSHIARPUR          8      8     8         8         8         8
      JALANDHAR          93     93    93        93        93        93
      KHANNA             17     17    17        17        17        17
      LUDHIANA           64     64    64        64        64        64
      PATIALA           119    119   119       119       119       119
RAJ   AJMER              16     16    16        16        16        16
      ALWAR              62     62    62        62        62        62
      BIKANER             9      9     9         9         9         9
      JAIPUR            147    147   147       147       147       147
      JODHPUR           132    132   132       132       132       132
      KOTA               25     25    25        25        25        25
      SRIGANGANAGAR       1      1     1         1         1         1
      UDAIPUR            75     75    75        75        75        75
TN    CHENNAI           147    147   147       147       147       147
      COIMBATORE         78     78    78        78        78        78
      DINDIGUL          161    161   161       161       161       161
      MADURAI             6      6     6         6         6         6
UP    AGRA              134    134   134       134       134       134
      ALIGARH            17     17    17        17        17        17
      BALLIA             12     12    12        12        12        12
      BAREILLY           17     17    17        17        17        17
      DEHRADOON          17     17    17        17        17        17
      DEORIA             33     33    33        33        33        33
      ETAWAH              2      2     2         2         2         2
      FARUKHABAD          1      1     1         1         1         1
      GORAKHPUR           4      4     4         4         4         4
      HALDWANI           10     10    10        10        10        10
      JHANSI              1      1     1         1         1         1
      KANPUR            146    146   146       146       146       146
      LUCKNOW           139    139   139       139       139       139
      MEERUT              1      1     1         1         1         1
      VARANASI           96     96    96        96        96        96
WB    BURDWAN            17     17    17        17        17        17
      KOLKATA           147    147   147       147       147       147
      MIDNAPUR            2      2     2         2         2         2
      PURULIA            17     17    17        17        17        17
      SHEROAPHULY         9      9     9         9         9         9

                     priceMod  date  lon  lat
state city
AP    HYDERABAD           137   137  137  137
      KURNOOL             142   142  142  142
      RAJAHMUNDRY           1     1    1    1
ASM   GUWAHATI            135   135  135  135
BHR   BIHARSHARIF           2     2    2    2
      PATNA               139   139  139  139
DEL   DELHI               159   159  159  159
GUJ   AHMEDABAD           126   126  126  126
      BHAVNAGAR           110   110  110  110
      DEESA                16    16   16   16
      GONDAL              164   164  164  164
      JAMNAGAR              6     6    6    6
      MAHUVA              211   211  211  211
      RAJKOT              157   157  157  157
      SURAT               147   147  147  147
HP    SHIMLA               40    40   40   40
HR    CHANDIGARH            3     3    3    3
      KARNAL              124   124  124  124
      RAIPUR              110   110  110  110
JH    RANCHI              123   123  123  123
JK    JAMMU               135   135  135  135
      SRINAGAR             29    29   29   29
KEL   TRIVENDRUM           55    55   55   55
KER   PALAYAM              14    14   14   14
KNT   BANGALORE           147   147  147  147
      BELGAUM             147   147  147  147
      BIJAPUR             130   130  130  130
      CHALLAKERE            1     1    1    1
      CHICKBALLAPUR        12    12   12   12
      DHAVANGERE          164   164  164  164
      HASSAN              123   123  123  123
      HUBLI               174   174  174  174
      KOLAR                12    12   12   12
      RAICHUR              17    17   17   17
MH    MUMBAI              147   147  147  147
      NAGPUR              130   130  130  130
MP    BHOPAL               44    44   44   44
      DEWAS                21    21   21   21
      INDORE              166   166  166  166
      MANDSOUR             18    18   18   18
      NEEMUCH               1     1    1    1
      SAGAR                17    17   17   17
      UJJAIN               44    44   44   44
MS    AHMEDNAGAR          144   144  144  144
      BOMBORI              29    29   29   29
      CHAKAN              153   153  153  153
      CHANDVAD             17    17   17   17
      DEVALA              122   122  122  122
      DHULIA              159   159  159  159
      DINDORI              41    41   41   41
      JALGAON             133   133  133  133
      JUNNAR               98    98   98   98
      KALVAN              115   115  115  115
      KOLHAPUR            144   144  144  144
      KOPERGAON            17    17   17   17
      LASALGAON           243   243  243  243
      LONAND              212   212  212  212
      MALEGAON            147   147  147  147
      MANMAD              219   219  219  219
      NANDGAON              6     6    6    6
      NASIK               142   142  142  142
      NEWASA               17    17   17   17
      NIPHAD              201   201  201  201
      PHALTAN              14    14   14   14
      PIMPALGAON          225   225  225  225
      PUNE                207   207  207  207
      RAHATA               17    17   17   17
      RAHURI              155   155  155  155
      SAIKHEDA            172   172  172  172
      SANGALI              58    58   58   58
      SANGAMNER           110   110  110  110
      SATANA               83    83   83   83
      SHRIRAMPUR          129   129  129  129
      SINNAR              207   207  207  207
      SOLAPUR             141   141  141  141
      SRIRAMPUR             3     3    3    3
      VANI                 83    83   83   83
      YEOLA               147   147  147  147
OR    BHUBNESWER          130   130  130  130
PB    ABOHAR               90    90   90   90
      AMRITSAR            122   122  122  122
      BHATINDA             86    86   86   86
      HOSHIARPUR            8     8    8    8
      JALANDHAR            93    93   93   93
      KHANNA               17    17   17   17
      LUDHIANA             64    64   64   64
      PATIALA             119   119  119  119
RAJ   AJMER                16    16   16   16
      ALWAR                62    62   62   62
      BIKANER               9     9    9    9
      JAIPUR              147   147  147  147
      JODHPUR             132   132  132  132
      KOTA                 25    25   25   25
      SRIGANGANAGAR         1     1    1    1
      UDAIPUR              75    75   75   75
TN    CHENNAI             147   147  147  147
      COIMBATORE           78    78   78   78
      DINDIGUL            161   161  161  161
      MADURAI               6     6    6    6
UP    AGRA                134   134  134  134
      ALIGARH              17    17   17   17
      BALLIA               12    12   12   12
      BAREILLY             17    17   17   17
      DEHRADOON            17    17   17   17
      DEORIA               33    33   33   33
      ETAWAH                2     2    2    2
      FARUKHABAD            1     1    0    0
      GORAKHPUR             4     4    4    4
      HALDWANI             10    10   10   10
      JHANSI                1     1    0    0
      KANPUR              146   146  146  146
      LUCKNOW             139   139  139  139
      MEERUT                1     1    1    1
      VARANASI             96    96   96   96
WB    BURDWAN              17    17   17   17
      KOLKATA             147   147  147  147
      MIDNAPUR              2     2    2    2
      PURULIA              17    17   17   17
      SHEROAPHULY           9     9    9    9

In [43]:
# q_pivot = pd.pivot_table(onion_df, values='quantity', index=['date','state'], columns=['state'], aggfunc=np.sum)
q_pivot = pd.pivot_table(onion_df, index=['date','state','city'])
q_pivot

                                   lat       lon  priceMax  priceMin  \
date       state city
1996-01-01 MS    LASALGAON    20.14914  74.23261     257.0     160.0
1996-02-01 MS    LASALGAON    20.14914  74.23261     229.0     133.0
1996-03-01 MS    LASALGAON    20.14914  74.23261     274.0     155.0
1996-04-01 MS    LASALGAON    20.14914  74.23261     279.0     136.0
1996-05-01 MS    LASALGAON    20.14914  74.23261     312.0     154.0
1996-06-01 MS    LASALGAON    20.14914  74.23261     413.0     229.0
1996-07-01 MS    LASALGAON    20.14914  74.23261     406.0     229.0
1996-08-01 MS    LASALGAON    20.14914  74.23261     388.0     164.0
1996-09-01 MS    LASALGAON    20.14914  74.23261     363.0     145.0
1996-10-01 MS    LASALGAON    20.14914  74.23261     560.0     160.0
1996-11-01 MS    LASALGAON    20.14914  74.23261     498.0     138.0
1996-12-01 MS    LASALGAON    20.14914  74.23261     451.0     138.0
1997-01-01 MS    LASALGAON    20.14914  74.23261     323.0     126.0
1997-02-01 MS    LASALGAON    20.14914  74.23261     305.0     134.0
1997-03-01 MS    LASALGAON    20.14914  74.23261     310.0     138.0
1997-04-01 MS    LASALGAON    20.14914  74.23261     240.0     149.0
1997-05-01 MS    LASALGAON    20.14914  74.23261     238.0     123.0
1997-06-01 MS    LASALGAON    20.14914  74.23261     237.0      64.0
1997-07-01 MS    LASALGAON    20.14914  74.23261     225.0      37.0
                 NIPHAD       20.07996  74.10931     161.0      47.0
                 PIMPALGAON   20.16997  73.98738     225.0      92.0
                 SAIKHEDA     22.96222  78.58312     193.0      80.0
                 SINNAR       19.85306  74.00063     161.0      34.0
1997-08-01 MS    LASALGAON    20.14914  74.23261     257.0      43.0
                 NIPHAD       20.07996  74.10931     230.0      78.0
                 PIMPALGAON   20.16997  73.98738     256.0     121.0
                 SAIKHEDA     22.96222  78.58312     219.0      95.0
                 SINNAR       19.85306  74.00063     215.0      21.0
1997-09-01 MS    LASALGAON    20.14914  74.23261     318.0      35.0
                 NIPHAD       20.07996  74.10931     274.0     108.0
                 PIMPALGAON   20.16997  73.98738     313.0     136.0
                 SAIKHEDA     22.96222  78.58312     270.0      97.0
                 SINNAR       19.85306  74.00063     271.0      16.0
1997-10-01 MS    LASALGAON    20.14914  74.23261     412.0      45.0
                 NIPHAD       20.07996  74.10931     389.0     123.0
                 PIMPALGAON   20.16997  73.98738     413.0     251.0
                 SAIKHEDA     22.96222  78.58312     376.0     129.0
                 SINNAR       19.85306  74.00063     352.0      31.0
1997-11-01 MS    LASALGAON    20.14914  74.23261     852.0     117.0
                 NIPHAD       20.07996  74.10931     720.0     243.0
                 PIMPALGAON   20.16997  73.98738     861.0     383.0
                 SAIKHEDA     22.96222  78.58312     641.0     240.0
                 SINNAR       19.85306  74.00063     634.0      74.0
1997-12-01 MS    LASALGAON    20.14914  74.23261    1144.0     118.0
                 PIMPALGAON   20.16997  73.98738    1255.0     415.0
                 SAIKHEDA     22.96222  78.58312     559.0      92.0
                 SINNAR       19.85306  74.00063    1003.0     143.0
1998-01-01 MS    CHAKAN       18.76027  73.86303    1633.0     333.0
                 LASALGAON    20.14914  74.23261    1447.0     225.0
                 LONAND       18.04171  74.18618    1640.0     910.0
                 MANMAD       20.25118  74.43660    1361.0     375.0
                 PIMPALGAON   20.16997  73.98738    1594.0     607.0
                 SAIKHEDA     22.96222  78.58312    1488.0     364.0
                 SINNAR       19.85306  74.00063    1538.0     223.0
1998-02-01 MS    CHAKAN       18.76027  73.86303    1142.0     175.0
                 LASALGAON    20.14914  74.23261    1126.0     267.0
                 LONAND       18.04171  74.18618    1053.0     438.0
                 MANMAD       20.25118  74.43660    1048.0     351.0
                 NIPHAD       20.07996  74.10931     878.0     163.0
                 PIMPALGAON   20.16997  73.98738    1151.0     581.0
                 SAIKHEDA     22.96222  78.58312    1024.0     472.0
                 SINNAR       19.85306  74.00063    1076.0     221.0
1998-03-01 GUJ   BHAVNAGAR    21.76447  72.15193     459.0     309.0
           MS    CHAKAN       18.76027  73.86303     419.0     184.0
                 LASALGAON    20.14914  74.23261     486.0     152.0
                 LONAND       18.04171  74.18618     397.0     293.0
                 MANMAD       20.25118  74.43660     510.0     231.0
                 NIPHAD       20.07996  74.10931     507.0     163.0
                 PIMPALGAON   20.16997  73.98738     535.0     326.0
                 SAIKHEDA     22.96222  78.58312     474.0     303.0
                 SINNAR       19.85306  74.00063     414.0      74.0
1998-04-01 GUJ   BHAVNAGAR    21.76447  72.15193     299.0     187.0
                 MAHUVA       21.09022  71.75632     299.0     181.0
           MS    CHAKAN       18.76027  73.86303     281.0     199.0
                 LASALGAON    20.14914  74.23261     318.0      76.0
                 LONAND       18.04171  74.18618     290.0     255.0
                 MANMAD       20.25118  74.43660     275.0     142.0
                 NIPHAD       20.07996  74.10931     304.0      67.0
                 PIMPALGAON   20.16997  73.98738     316.0     166.0
                 SAIKHEDA     22.96222  78.58312     269.0     156.0
                 SINNAR       19.85306  74.00063     272.0      38.0
1998-05-01 GUJ   BHAVNAGAR    21.76447  72.15193     325.0     150.0
                 MAHUVA       21.09022  71.75632     331.0     199.0
           MS    CHAKAN       18.76027  73.86303     382.0     208.0
                 LASALGAON    20.14914  74.23261     381.0      97.0
                 LONAND       18.04171  74.18618     406.0     325.0
                 MANMAD       20.25118  74.43660     318.0     181.0
                 NIPHAD       20.07996  74.10931     340.0     135.0
                 PIMPALGAON   20.16997  73.98738     381.0     207.0
                 SAIKHEDA     22.96222  78.58312     337.0     216.0
                 SINNAR       19.85306  74.00063     343.0      50.0
1998-06-01 GUJ   MAHUVA       21.09022  71.75632     490.0     327.0
           MS    CHAKAN       18.76027  73.86303     699.0     256.0
                 LASALGAON    20.14914  74.23261     703.0     158.0
                 LONAND       18.04171  74.18618     607.0     483.0
                 MANMAD       20.25118  74.43660     625.0     292.0
                 NIPHAD       20.07996  74.10931     610.0     294.0
                 PIMPALGAON   20.16997  73.98738     682.0     435.0
                 SAIKHEDA     22.96222  78.58312     744.0     346.0
                 SINNAR       19.85306  74.00063     719.0     112.0
1998-07-01 GUJ   MAHUVA       21.09022  71.75632     805.0     453.0
           MS    CHAKAN       18.76027  73.86303     950.0     439.0
                 LASALGAON    20.14914  74.23261     932.0     263.0
                 LONAND       18.04171  74.18618     870.0     680.0
                 MANMAD       20.25118  74.43660     896.0     588.0
                 NIPHAD       20.07996  74.10931     897.0     590.0
                 PIMPALGAON   20.16997  73.98738     935.0     691.0
                 SAIKHEDA     22.96222  78.58312     881.0     549.0
                 SINNAR       19.85306  74.00063     907.0     330.0
1998-08-01 GUJ   MAHUVA       21.09022  71.75632    1342.0     743.0
           MS    CHAKAN       18.76027  73.86303    1603.0     459.0
                 LASALGAON    20.14914  74.23261    1459.0     332.0
                 LONAND       18.04171  74.18618    1250.0     667.0
                 MANMAD       20.25118  74.43660    1427.0     738.0
                 NIPHAD       20.07996  74.10931    1460.0     953.0
                 PIMPALGAON   20.16997  73.98738    1468.0    1129.0
                 SAIKHEDA     22.96222  78.58312    1485.0    1029.0
                 SINNAR       19.85306  74.00063    1463.0     215.0
1998-09-01 GUJ   MAHUVA       21.09022  71.75632    1594.0     888.0
           MS    CHAKAN       18.76027  73.86303    2042.0    1017.0
                 LASALGAON    20.14914  74.23261    2001.0     386.0
                 LONAND       18.04171  74.18618    1583.0    1267.0
                 MANMAD       20.25118  74.43660    1792.0    1219.0
                 NIPHAD       20.07996  74.10931    2038.0    1045.0
                 PIMPALGAON   20.16997  73.98738    1952.0    1610.0
                 SAIKHEDA     22.96222  78.58312    1864.0    1303.0
                 SINNAR       19.85306  74.00063    2024.0     396.0
1998-10-01 GUJ   BHAVNAGAR    21.76447  72.15193    2250.0    1000.0
                 MAHUVA       21.09022  71.75632    1996.0    1233.0
           MS    CHAKAN       18.76027  73.86303    2463.0    1050.0
                 LASALGAON    20.14914  74.23261    2954.0     500.0
                 LONAND       18.04171  74.18618    2533.0    1400.0
                 MANMAD       20.25118  74.43660    2638.0     800.0
                 NIPHAD       20.07996  74.10931    3365.0    1113.0
                 PIMPALGAON   20.16997  73.98738    3051.0    2197.0
                 SAIKHEDA     22.96222  78.58312    2925.0    1900.0
                 SINNAR       19.85306  74.00063    2863.0     288.0
1998-11-01 GUJ   BHAVNAGAR    21.76447  72.15193    1900.0    1500.0
                 MAHUVA       21.09022  71.75632    1452.0     693.0
           MS    CHAKAN       18.76027  73.86303    1779.0     500.0
                 LASALGAON    20.14914  74.23261    2080.0     245.0
                 LONAND       18.04171  74.18618    1988.0    1275.0
                 MANMAD       20.25118  74.43660    1708.0     890.0
                 PIMPALGAON   20.16997  73.98738    2061.0     892.0
                 SINNAR       19.85306  74.00063    1697.0     150.0
1998-12-01 GUJ   BHAVNAGAR    21.76447  72.15193    1168.0     883.0
                 MAHUVA       21.09022  71.75632    1132.0     788.0
           MS    CHAKAN       18.76027  73.86303    1385.0     344.0
                 LASALGAON    20.14914  74.23261    1152.0     442.0
                 LONAND       18.04171  74.18618    1375.0     925.0
                 MANMAD       20.25118  74.43660    1162.0     767.0
                 PIMPALGAON   20.16997  73.98738    1180.0     847.0
                 SINNAR       19.85306  74.00063    1219.0     219.0
1999-01-01 GUJ   BHAVNAGAR    21.76447  72.15193     523.0     447.0
                 MAHUVA       21.09022  71.75632     553.0     393.0
           MS    CHAKAN       18.76027  73.86303     681.0     157.0
                 LASALGAON    20.14914  74.23261     545.0     310.0
                 LONAND       18.04171  74.18618     617.0     333.0
                 MANMAD       20.25118  74.43660     562.0     449.0
                 PIMPALGAON   20.16997  73.98738     558.0     411.0
                 PUNE         18.52043  73.85674     648.0     313.0
                 SINNAR       19.85306  74.00063     524.0     175.0
1999-02-01 GUJ   BHAVNAGAR    21.76447  72.15193     332.0     276.0
                 MAHUVA       21.09022  71.75632     333.0     249.0
           MS    CHAKAN       18.76027  73.86303     361.0     200.0
                 LASALGAON    20.14914  74.23261     347.0     140.0
                 LONAND       18.04171  74.18618     284.0     144.0
                 MANMAD       20.25118  74.43660     304.0     209.0
                 NIPHAD       20.07996  74.10931     353.0     185.0
                 PIMPALGAON   20.16997  73.98738     360.0     250.0
                 PUNE         18.52043  73.85674     379.0     238.0
                 SAIKHEDA     22.96222  78.58312     304.0     186.0
                 SINNAR       19.85306  74.00063     278.0     107.0
1999-03-01 GUJ   BHAVNAGAR    21.76447  72.15193     304.0     225.0
                 MAHUVA       21.09022  71.75632     317.0     210.0
           MS    CHAKAN       18.76027  73.86303     338.0     188.0
                 LASALGAON    20.14914  74.23261     292.0     110.0
                 LONAND       18.04171  74.18618     292.0     217.0
                 MANMAD       20.25118  74.43660     258.0     134.0
                 NIPHAD       20.07996  74.10931     264.0     125.0
                 PIMPALGAON   20.16997  73.98738     265.0     162.0
                 PUNE         18.52043  73.85674     333.0     245.0
                 SAIKHEDA     22.96222  78.58312     274.0     157.0
                 SINNAR       19.85306  74.00063     254.0      57.0
1999-04-01 GUJ   BHAVNAGAR    21.76447  72.15193     358.0     230.0
                 MAHUVA       21.09022  71.75632     370.0     220.0
           MS    CHAKAN       18.76027  73.86303     440.0     243.0
                 LASALGAON    20.14914  74.23261     468.0     119.0
                 LONAND       18.04171  74.18618     381.0     232.0
                 MANMAD       20.25118  74.43660     391.0     146.0
                 NIPHAD       20.07996  74.10931     453.0     149.0
                 PIMPALGAON   20.16997  73.98738     464.0     218.0
                 PUNE         18.52043  73.85674     400.0     252.0
                 SAIKHEDA     22.96222  78.58312     407.0     181.0
                 SINNAR       19.85306  74.00063     407.0      51.0
1999-05-01 GUJ   BHAVNAGAR    21.76447  72.15193     425.0     350.0
                 MAHUVA       21.09022  71.75632     451.0     218.0
           MS    CHAKAN       18.76027  73.86303     586.0     200.0
                 LASALGAON    20.14914  74.23261     648.0     180.0
                 LONAND       18.04171  74.18618     521.0     250.0
                 MANMAD       20.25118  74.43660     537.0     143.0
                 NIPHAD       20.07996  74.10931     599.0     160.0
                 PIMPALGAON   20.16997  73.98738     616.0     334.0
                 PUNE         18.52043  73.85674     555.0     317.0
                 SAIKHEDA     22.96222  78.58312     514.0     232.0
                 SINNAR       19.85306  74.00063     547.0      96.0
1999-06-01 GUJ   MAHUVA       21.09022  71.75632     392.0     213.0
           MS    CHAKAN       18.76027  73.86303     499.0     214.0
                 LASALGAON    20.14914  74.23261     554.0     186.0
                 LONAND       18.04171  74.18618     505.0     320.0
                 MANMAD       20.25118  74.43660     485.0     197.0
                 NIPHAD       20.07996  74.10931     530.0     205.0
                 PIMPALGAON   20.16997  73.98738     548.0     311.0
                 PUNE         18.52043  73.85674     531.0     313.0
                 SAIKHEDA     22.96222  78.58312     458.0     265.0
                 SINNAR       19.85306  74.00063     477.0      64.0
1999-07-01 GUJ   MAHUVA       21.09022  71.75632     514.0     315.0
           MS    CHAKAN       18.76027  73.86303     485.0     150.0
                 LASALGAON    20.14914  74.23261     483.0     188.0
                 LONAND       18.04171  74.18618     461.0     200.0
                 MANMAD       20.25118  74.43660     463.0     245.0
                 NIPHAD       20.07996  74.10931     493.0     240.0
                 PIMPALGAON   20.16997  73.98738     501.0     304.0
                 PUNE         18.52043  73.85674     548.0     302.0
                 SAIKHEDA     22.96222  78.58312     459.0     278.0
                 SINNAR       19.85306  74.00063     463.0      59.0
1999-08-01 GUJ   MAHUVA       21.09022  71.75632     441.0     307.0
           MS    CHAKAN       18.76027  73.86303     467.0     219.0
                 LASALGAON    20.14914  74.23261     427.0     177.0
                 LONAND       18.04171  74.18618     477.0     260.0
                 MANMAD       20.25118  74.43660     417.0     242.0
                 NIPHAD       20.07996  74.10931     427.0     245.0
                 PIMPALGAON   20.16997  73.98738     433.0     341.0
                 PUNE         18.52043  73.85674     485.0     333.0
                 SAIKHEDA     22.96222  78.58312     428.0     297.0
                 SINNAR       19.85306  74.00063     434.0      92.0
1999-09-01 GUJ   MAHUVA       21.09022  71.75632     660.0     455.0
           MS    CHAKAN       18.76027  73.86303     716.0     229.0
                 LASALGAON    20.14914  74.23261     659.0     206.0
                 LONAND       18.04171  74.18618     673.0     463.0
                 MANMAD       20.25118  74.43660     643.0     415.0
                 NIPHAD       20.07996  74.10931     663.0     329.0
                 PIMPALGAON   20.16997  73.98738     664.0     482.0
                 PUNE         18.52043  73.85674     678.0     476.0
                 SAIKHEDA     22.96222  78.58312     652.0     415.0
                 SINNAR       19.85306  74.00063     691.0     163.0
1999-10-01 GUJ   MAHUVA       21.09022  71.75632     619.0     384.0
           MS    CHAKAN       18.76027  73.86303     640.0     200.0
                 LASALGAON    20.14914  74.23261     664.0     202.0
                 LONAND       18.04171  74.18618     546.0     250.0
                 MANMAD       20.25118  74.43660     617.0     335.0
                 NIPHAD       20.07996  74.10931     659.0     267.0
                 PIMPALGAON   20.16997  73.98738     662.0     440.0
                 PUNE         18.52043  73.85674     658.0     369.0
                 SAIKHEDA     22.96222  78.58312     647.0     427.0
                 SINNAR       19.85306  74.00063     619.0     122.0
1999-11-01 GUJ   MAHUVA       21.09022  71.75632     448.0     250.0
           MS    CHAKAN       18.76027  73.86303     639.0     189.0
                 LASALGAON    20.14914  74.23261     537.0     157.0
                 LONAND       18.04171  74.18618     525.0     253.0
                 MANMAD       20.25118  74.43660     481.0     221.0
                 NIPHAD       20.07996  74.10931     522.0     224.0
                 PIMPALGAON   20.16997  73.98738     487.0     239.0
                 PUNE         18.52043  73.85674     603.0     332.0
                 SAIKHEDA     22.96222  78.58312     522.0     321.0
                 SINNAR       19.85306  74.00063     524.0      59.0
1999-12-01 GUJ   BHAVNAGAR    21.76447  72.15193     304.0     180.0
                 MAHUVA       21.09022  71.75632     323.0     186.0
           MS    CHAKAN       18.76027  73.86303     431.0     145.0
                 LASALGAON    20.14914  74.23261     350.0     153.0
                 LONAND       18.04171  74.18618     331.0     168.0
                 MANMAD       20.25118  74.43660     337.0     198.0
                 NIPHAD       20.07996  74.10931     301.0     185.0
                 PIMPALGAON   20.16997  73.98738     357.0     209.0
                 PUNE         18.52043  73.85674     462.0     259.0
                 SAIKHEDA     22.96222  78.58312     348.0     213.0
                 SINNAR       19.85306  74.00063     323.0      98.0
2000-01-01 GUJ   BHAVNAGAR    21.76447  72.15193     253.0     199.0
                 MAHUVA       21.09022  71.75632     247.0     149.0
           MS    CHAKAN       18.76027  73.86303     295.0     103.0
                 LASALGAON    20.14914  74.23261     341.0     145.0
                 LONAND       18.04171  74.18618     293.0     137.0
                 MANMAD       20.25118  74.43660     256.0     161.0
                 NIPHAD       20.07996  74.10931     234.0     151.0
                 PIMPALGAON   20.16997  73.98738     274.0     181.0
                 PUNE         18.52043  73.85674     320.0     169.0
                 SAIKHEDA     22.96222  78.58312     243.0     151.0
                 SINNAR       19.85306  74.00063     289.0     109.0

In [44]:
# testing if the pivottable calculations are correct
onion_df.loc[(onion_df['city'] == 'DELHI') & (onion_df['year'] == 2008) & (onion_df['month'] == 'September'), 'quantity'].sum()

273808

In [46]:
# exporting the pivottable to csv for plotting
q_pivot.to_csv('../onion/data/onion_q.csv')